name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmM3ZDlkNTUtMzIxZS00YjZjLThlZGMtNDY2YWJiOTAxODA1IiwidGVuYW50X2lkIjoiNDBhMjcwNTJhNTFlNDIzN2U2MTY4YjViMWE3NDg5ZTMxOWQ4OGY5YWU0MDNmYjg4ZWU0MjVjZDY3YzcwNDg1MSIsImludGVybmFsX3NlY3JldCI6IjRhOWVkN2NhLTIwNzktNDQ3MS1iYmRiLWU1OGY0NTA0YmFjMyJ9.xOyLb50iLnAw8nLU5NYO9Fn0iW8X5pjSVKAndQkLuFw"

JWT_SECRET="amit1secret"

